services:
  fabricai-inference-server:
    build: .
    container_name: fabricai-inference-server
    env_file: .env
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - redis
      - ollama

  redis:
    image: "redis:7.0"
    command:
      - redis-server
      - --save
      - "60 1000"
      - --maxmemory
      - 256mb
      - --maxmemory-policy
      - allkeys-lru
    volumes:
      - redis_data:/data

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  redis_data:
  ollama_data:
